import { Qasida, TextSize } from './types';

export const QASIDAS: Qasida[] = [
  {
    id: 'taaniyatu-rabeehi',
    title: 'TANIYATUN RABBI',
    verses: [
      { id: 'tr-1', lines: ["Lii saadatun min hizihim Inlam aqun min'um falii", "Aqdaamuhum faoqal jibaa Bihubihim hizzu wajaa"] },
      { id: 'tr-2', lines: ["Fabijaahihim wabihizihim Waqtim lanaa bil'hayril yaa", "Toyyib lanaa ayshal ayaa Man laa lanaa rabbu siwaa"] },
      { id: 'tr-3', lines: ["Yaa rabbanaa solli alaa Alaa samaawaatil ula", "Khayril anaami man alaa Bi izni rabbihil alii"] },
      { id: 'tr-4', lines: ["Tahni'atu rrabeehi Bil mantiqil baadihi", "Bimidhati shafeehi Abgii bihaa mu'amalii"] },
      { id: 'tr-5', lines: ["Ahlan bisha'ril maolidi Sha'rin Nabiyyi Ahmadi", "Sha'ril ulaa was su'dadi Sha'ri rabeehil awwali"] },
      { id: 'tr-6', lines: ["Qad uzzo bi-rabeehi Lil ardi waa shefeehi", "Iz kaana kaa rRobeehi Bikulli khatbin mu'dili"] },
      { id: 'tr-7', lines: ["Ahlan bisha'ril farahi Wa fakhrinaa wal marahi", "Sha'ri zahaabi tarahi Sha'rin Nabiyyil afdoli"] },
      { id: 'tr-8', lines: ["Sha'ril falaahi was-suruuri Muwashahi bayna shuhuuri", "Sha'ri bihi saada duhuuri Mutawajin mukallali"] },
      { id: 'tr-9', lines: ["Ahlan bisha'ril faatihi Man usso bil-fawaatihi", "Iglaaqi kaonil faatihi Wahaaza khatmal milali"] },
      { id: 'tr-10', lines: ["Ahlan bisha'ril khaatimi Wafaatihi wa khatimi", "Sha'ri nnabiyyi qosimi Wa A'akhirin wa awwali"] },
      { id: 'tr-11', lines: ["Ahlan bisha'rin Naasiri Bil Urfi sha'ri Zohiri", "Lil-aqqi sha'ril A'amiri Bikulli wasfin Akmal"] },
      { id: 'tr-12', lines: ["Ahlan bisha'ril haadi Wa qohidin wahaadii", "Liman'aji Rashaadi Ilaa toreeqinl Amthali"] },
      { id: 'tr-13', lines: ["Ahlan bisha'ri seyyidi Man haasa sabqo su'dadi", "Li-a'mari wa aswadi Yaoma i'tizaari rusuli"] },
      { id: 'tr-14', lines: ["Waqod kafaahaa kullahaa Biqaolihi Anaa lahaa", "A'baahahaa wakullaha Inda 'ishtidaadil wajali"] },
      { id: 'tr-15', lines: ["Fayaa lahaa min khuto Min robbihi sal tu'to", "Jawaabuhu fil ukhto Washfa'a ladaynaa tuqbalu"] },
      { id: 'tr-16', lines: ["Ahlan bisha'ril mustafaa Wa khayri abdii qod sofaa", "Sofwatu kullu mustofa Min malikin ao mursalin"] },
      { id: 'tr-17', lines: ["Wa sha'ri khayril khalqi Sha'ri azeemil khalqi", "Sha'ri jemeelul khalqi Fil mu'kamil munazzali"] },
      { id: 'tr-18', lines: ["Sha'ri ladhii Azarahu Min ubbihi khayyarahu", "Ilaahuhu wa'khtarahu Hinda' inqido-ohil ajali"] },
      { id: 'tr-19', lines: ["Sha'ri llazzi maa saaha qottu Alayhi jibreelun abati", "Waman lahul usnaa faqot Bikulli Nnuuri mu'tali"] },
      { id: 'tr-20', lines: ["Ahlan bilayli isnaa ashar Wateebi zaalika sahar", "Feehi wayaomihi-l- agar Wanuuru Hufqihi-l-jeli"] },
      { id: 'tr-21', lines: ["Ahlan bikulli maa thohari Feehi karofhihil basori", "min khariqin yahyal fiqari Ilaa maqo-omihil alii"] },
      { id: 'tr-22', lines: ["Wa maa rahathu min ajab Sabaobatan thuma iqtarab", "Aminatu heena nasob Bisajdati-l-mubtahili"] },
      { id: 'tr-23', lines: ["Kama tadallaa Zuhuru Feehi wahalla-l- kasru", "Kama taraa-al qos-ru Bi-sonomi-l- mujdali"] },
      { id: 'tr-24', lines: ["Wagaadoti-l-bihaaru Min ajlihi wan-naari", "Wajaffati-l- anhaaru Qod tofi-at min khajali"] },
      { id: 'tr-25', lines: ["Wajinnuhum fee nakadin Wa-azlihaa an moghadi", "Laram-yihaa bi-rosodi Min ajli khayri rusuli"] },
      { id: 'tr-26', lines: ["Waran-natu shaytaani Min ao-dohil burhaani", "Jazaa azeemu sha'ani Li-azmi maa bihib-tuli"] },
      { id: 'tr-27', lines: ["Qod manna dhul-ifdoli Fil afdoli layaalii", "Bi-afdoli rijaali Bil-baladil mufadoli"] },
      { id: 'tr-28', lines: ["Ahlan biyaomi heedin Qod alla fil maolidi", "Maa mizluhu min heedin Feehi mahallu zuhalin"] },
      { id: 'tr-29', lines: ["Wasaa-bihil - wilaada Min wifqin maa araada", "wamaa ataahu shaa-da ilaa-huhu fil azali"] },
      { id: 'tr-30', lines: ["Ahlan biyaomi summii Ramsan lima'na-l-ismi", "Muhammadan khayras-smin Min jaddihi layanjali"] },
      { id: 'tr-31', lines: ["Bihamdi-l-Awwaleena Fakaana zaa yekeenaa", "Lahu wal-haakhireena Minal kareemil mufdoli"] },
      { id: 'tr-32', lines: ["Ahlan biyaomi iznayni Mabhazu sirril-kaoni", "Maolidi zaani-iznayni Moq-damihil mubajjali"] },
      { id: 'tr-33', lines: ["Akrim bi-sha'ril hajami Akrim bi-ardil harami", "Ibreela sha'ril karami Maolidi khayri mursali"] },
      { id: 'tr-34', lines: ["Akrim biyaomin so-oraa", "Ishreena was-tano-oran"] },
      { id: 'tr-35', lines: ["Liman hawaa-s-tano-oraa Akrim bisha'ri Neesaani Qudwati A'alil ihisaani", "Wagufratun min monzili Maolidi khayri insaani Wal kaamilil mukammali"] },
      { id: 'tr-36', lines: ["Qod tammati laa-haali Bizeenatil mahaalii", "Fee uddati laayaalee Kal-jaoharil mufadoli"] },
      { id: 'tr-37', lines: ["Ta'nihatun robeehi Bil-mantiqil badeehi", "Bimid-hati shaafeehi Abgii biha muhammali"] },
      { id: 'tr-38', lines: ["Abgii bihaal jamha bihi Wafadli hubbi Robbihi", "Yaoman wanayla qurbihi Waman rido-ohu amalii"] },
      { id: 'tr-39', lines: ["Wal-khatma lee bil-husnaa Ladaal moqo-oril asnaa", "Wal-jamha lee fil husnaa Mahaa rofeeqi-l-afdoli"] },
      { id: 'tr-40', lines: ["Wakun lanaa waleeyan Laa-na'khtashi gawiyyan", "Wan-naasiran hafiyan Bijaahi abdeekal-allee"] },
      { id: 'tr-41', lines: ["Solli wasallama -l- ilaa` Maa daama kaonuhu illaa", "Alayhi afdolu solaata Min abada li-asali"] },
      { id: 'tr-42', lines: ["Wa-haalihi wasahbihi Wakulli aali khubbihi", "Wasaojihi wa hisbihi Maha salaamil akmali"] },
      { id: 'tr-43', lines: ["Bijaahihim yaa ilaahi igfir linaasimihaa Wahumahum bikhafiyin lutfi wakfihim", "Wasma' liqohreeha walillazii hadora Nawaa-hiba d-dahri maha aafaatihil kadara"] },
      { id: 'tr-44', lines: ["Ajib duhaa-hahum wa-ajjil billazi tolabuu", "Bihaahi Ahmada maha ashaabihil khayara"] },
    ]
  },
  {
    id: 'ahlan-bishari',
    title: "AHLAN BISHA'RI",
    verses: [
      { id: 'ab-1', lines: ["Ahlan bisha'ril maolidi Aslal usuuli liseyyidi", "Zakkara bil mahatadi Habeebinaal mubajjali"] },
      { id: 'ab-2', lines: ["Qod kaana khayra mursali Walam yakun min jandali", "Qoblal wujuudil awwali Li aslinaal mu'assoli"] },
      { id: 'ab-3', lines: ["Lam yadri khayral khalqi Siwal ilaahil haqqi", "Fi khulqihi wal khuluqi Min malakii Ao mursali"] },
      { id: 'ab-4', lines: ["Fasha'nuhu sha'nu ajib Ramsul habeebi lil-habeeb", "Wa ramsuhu ramsul habeeb Fil uruufi gayru mushkili"] },
      { id: 'ab-5', lines: ["Yaa lal-imaamil mu'talaa aolaahu daama mushkila", "Mataa ajaaba bibalaa Li-usmi maa qod yanjalii"] },
      { id: 'ab-6', lines: ["Laolal habeebul murtadho Wadeenuhu lladhi-irtadho", "Maa neela maazaa yurtadho Ilaahuhu fil azali"] },
      { id: 'ab-7', lines: ["Ahlan bihi iz-umila Mufakhomaa mubajjala", "Ahlan bihi iz-nasalaa Qod faaqo kulla rusuli"] },
      { id: 'ab-8', lines: ["Ahlan bihi iz-ursilaa Wa naala zikran munsala", "Wa-iz saraa wanazalaa Wa laysa bil mubaddali"] },
      { id: 'ab-9', lines: ["Ahlan bihi heena talaa Wa nuuruhu taha-sola", "Sabhal mathaanii musjala Min majdihil mu'athali"] },
      { id: 'ab-10', lines: ["Ahlan bimihraabil wujuud Ahlan bizaalikal waduud", "Ahlan bihi ayni shuhuud Wanaasili munas-sali"] },
      { id: 'ab-11', lines: ["Ahlan bihi min faadili Muwasolin wakaamili", "Mufaddoli wa-waasilin Fi-Naasi khayri mukmali"] },
      { id: 'ab-12', lines: ["Ahlan bihi min maajidin Muhammadin wawaajidi", "Mumajjadin wahaamidin Wamuujidi mukhawali"] },
      { id: 'ab-13', lines: ["Ahlan bihi min a-abidin Qo-otili kulli a-abidin", "Mujaahidin wa shahidin Lil-aqqi ma'maa yanjalii"] },
      { id: 'ab-14', lines: ["Ahlan bihi iz-jaahanaa Min mu'dilin qod saa'ana", "Minnaa bidafhi maa lanaa Bal kullu shayhin mushkili"] },
      { id: 'ab-15', lines: ["Yaa Rabaanaa solli alaa Man khasohul haqqu alaa", "Nuuril ilaahil mu'tala Bil mu'kamil munassali"] },
      { id: 'ab-16', lines: ["Solli alaa mon umaru Min nuurihi wasuwaru", "Lam yadrihi wa suwaru Madhun lahu minal alii"] },
      { id: 'ab-17', lines: ["Solli alaa min sajadat Amlaaku robbi U'kimat", "Linuurihi iz-basurat Aayaatuhu fil asali"] },
      { id: 'ab-18', lines: ["Solli alaal iz-nayni Wasiruuhu fiz-nayni", "Zumrati kulli iz-nayni Wa saaka sirrun asalii"] },
      { id: 'ab-19', lines: ["Solli alaal basheeri Biqodrihil kabeeri", "Heena ataa n-naazeeri Wal tu'tee lii muhammali"] },
      { id: 'ab-20', lines: ["Solli alaa mahmuudin Wamanbahi shuhuudi", "Muhammadin zil juudi Wa ayni sirri yanjali"] },
      { id: 'ab-21', lines: ["Solli alaa mon mon azomu Mazza jeheemi mudtorim", "Maolidahu haqqon urimu Bifadli robbi mujsili"] },
      { id: 'ab-22', lines: ["Solli alaa mon mon ador Yakuunu mizla mon sobar", "Maolidahu ma'maa sukir Biyaomi badril mursali"] },
      { id: 'ab-23', lines: ["Wa kullu mon jaada bishayhi Karaamatan lil-khayri Hai", "Li-maolidil mukhtari Hai Fa-innahu kaman walee"] },
      { id: 'ab-24', lines: ["Yaa Robbanaa fagfir lanaa Wa-tataqobbal sa'yanaa", "Wal ta'fu annaa wakfina Bijaahi aazal akmali"] },
      { id: 'ab-25', lines: ["Wal-ta'dinaa wa'di binaa Wa naslanaa wa a'lanaa", "Wa najjeena wa roqqina Wa sahbanaa waman walii"] },
      { id: 'ab-26', lines: ["Wal takfi annaal kulafaa Wana-yyiranna suhafaa", "Walil ginaa wal tuhafaa Yaoma-sh-tidaadil wajali"] },
      { id: 'ab-27', lines: ["Warsuk lanaal uluumaa Wak-shif lanaal guyuumaa", "Wa tu'tinaal fuhuumaa Bijaahi khayril mursali"] },
      { id: 'ab-28', lines: ["Wasoliyyan yaa Rabbanaa Waso'hbihi waman danaa", "Alaa Rasuuli hibeena Wakullu qofwin amzali"] },
      { id: 'ab-29', lines: ["Wak-shif libar'haamal ijaab Wamaa lahu minal sihaab", "Wanajjihi minal iqob Bil-kaamilil mukammali"] },
    ]
  },
  {
    id: 'wakafaani',
    title: 'WAKAFAANIY',
    verses: [
      { id: 'wk-1', lines: ["So-ori man waslal gawaani War'mi bil-beedil hisaani", "Wa'tazil sikral agaani Was'lu makhtuma dinaani"] },
      { id: 'wk-2', lines: ["Wal-malaahii wal-magaani Kullu zee-wayka saraabu", "Min kiraani Ao mabaani Wabgi ruuhan lil-mahaanee"] },
      { id: 'wk-3', lines: ["Ayna haahin aqqo aqqin Bisifaati saati haqqon", "Taaliyaa sab'hal mathaani Rutbatan laysati lisaani"] },
      { id: 'wk-4', lines: ["Fahuwa mukhtaarul baraaya Barasati adraatu to-oha", "Qoblaa takweenil kiyaani Qobla takweenil makaani"] },
      { id: 'wk-5', lines: ["Barasati adraatu to-oha Barasati adraatu to-oha", "Qobla takweenil makaani Qobla takweenil makaani"] },
      { id: 'wk-6', lines: ["Fahuwa Aklii washaraabi Wahuwa Hunzii wahuwa kanzee", "wahuwa deenii wajanaani Wa ameenii wa amaani"] },
      { id: 'wk-7', lines: ["Wa-rofiqii wa-toriqii Wa-rubuuhii wa-qusuuri", "Wa-jawaadi wa-sinaani Wahuwa khayratul hisaani"] },
      { id: 'wk-8', lines: ["Wahuwa bayhii wa-sharohi Laysa lii gayrul muqoffa", "Wahuwa arzii wa-jinaani Walizaa taama janaani"] },
      { id: 'wk-9', lines: ["Laa taraa sikra siwaahu Ini-araa sikru siwaahu", "Fee fu'aadii wa lisaanii Gayra la'wii wamajaani"] },
      { id: 'wk-10', lines: ["Wa'tidaahii lisiwaahu Innanii tuula ayaatii", "Tayfu janna laa hara'nii Rabbu amnin wa-amaani"] },
      { id: 'wk-11', lines: ["Laan'tisorii bil mufadda Fafuhaadii muz-ramaani", "Wahuwa aynii wa'ayaanii Fii jadeedil aymanaani"] },
      { id: 'wk-12', lines: ["Wa-habeebii muz shafaani Wahuwal abdu wa'aydon", "Wa-sofaa lii qod mahaanii Ramsuhu haahu tadaani"] },
      { id: 'wk-13', lines: ["Wahuwa aynul ismi wal-ar Wa-habeebun wa-mahaadi", "fi lita'qeeqil mahaani fee taqosin wa-tadaani"] },
      { id: 'wk-14', lines: ["Wahuwa daahi wada-waahii Laytahul waqta habaanii", "Qod baraani wa-shafaani Waslahu wahuwa kafaani"] },
      { id: 'wk-15', lines: ["Daahu shaoqee kulla waqtin Sullu nafsee waha-waahi", "Fee shadeedil ayyajaani Maf'khari raodul jinaani"] },
      { id: 'wk-16', lines: ["Maa baqo lii min baqohi Wa sefeerii wa bukaahi", "Min qaramee wa-anaani Wa araanii laa araani"] },
      { id: 'wk-17', lines: ["Laa-imii faaraz lahaali Kam khaleelin qod jafaani", "Qod dahaani maa dahaani Ligaraamii wa-ramaani"] },
      { id: 'wk-18', lines: ["Rubba sinwin quntu arjuu Wa nahaanii wala-haanii", "Wasluhu thumma jafaani Wa shajaanii wa-nafaanii"] },
      { id: 'wk-19', lines: ["Layza lil yaoma khaleelu Gayru haaza qod qolaani", "Gayru maa minka ataani Aazilan lee kulla Aani"] },
      { id: 'wk-20', lines: ["Mazzaquu jildee jihaaran Duuna zambin gayra anni", "Kha'arujuuni min makaani Ubbu toha fil janaani"] },
      { id: 'wk-21', lines: ["Wa araanii lasta ulfaa Wa-araa lao mazzaquuni", "Taahiban maral awaanii Bi-mawaadil Undu-waani"] },
      { id: 'wk-22', lines: ["Lam yanaaluu maa Araadu Allaluuni jeerati min", "Qod madoo zaa wakafaani Zikra man yatluul mathaani"] },
      { id: 'wk-23', lines: ["Raddadu lee zikrahu hee Wakafaani toha hiban", "Na sofaa lee wa-amaani Laa ubaali liman qolaani"] },
      { id: 'wk-24', lines: ["Wakafaani toha hiban Lastu a'khsha kayda a'adaa", "Laa ubaali liman qolaani i walaa jaora zamaani"] },
      { id: 'wk-25', lines: ["Famakaani fee zamaani Wa solaatun wa salaamun", "Wa zamaani fee makaani Fee tasoreefil awaani"] },
      { id: 'wk-26', lines: ["Man zawaati zaati tatraa Thumma aalin wa-sihaabi", "Nahwa toha maa kafaani Sooramuu waslal gawaani"] },
    ]
  },
  {
    id: 'yaa-nabiyyu',
    title: 'YAA NABIYYU',
    verses: [
      { id: 'yn-1', lines: ["TALA 'AL BADRU 'ALAYNAA", "LABAYKA YAA RASUULA LLAH"] },
      { id: 'yn-2', lines: ["MIN THANIYAATIL WADAA'I", "LABAYKA YAA RASUULA LLAH"] },
      { id: 'yn-3', lines: ["WAJABA SHUKRU 'ALAYNA", "LABAYKA YAA RASUULA LLAH"] },
      { id: 'yn-4', lines: ["MADA 'AA LILLAHI DAA'I", "LABAYKA YAA RASUULA LLAH"] },
      { id: 'yn-5', lines: ["AYYUHAL MAB'UUTHU FEENA", "LABAYKA YAA RASUULA LLAH"] },
      { id: 'yn-6', lines: ["JI'TA BIL AMRIL MUTA'I", "LABAYKA YAA RASUULA LLAH"] },
      { id: 'yn-7', lines: ["JI'TA SHARAFTAL MADEENAH", "LABAYKA YAA RASUULA LLAH"] },
      { id: 'yn-8', lines: ["MARHABAN YAA KHAYRA DAA'I", "LABAYKA YAA RASUULA LLAH"] },
      { id: 'yn-9', lines: ["ANTA SHAMSUN ANTA BADRUN", "LABAYKA YAA RASUULA LLAH"] },
      { id: 'yn-10', lines: ["ANTA NUURUN FAOQO NUURIN", "LABAYKA YAA RASUULA LLAH"] },
      { id: 'yn-11', lines: ["ANTA IKSEERU WA GAALII", "LABAYKA YAA RASUULA LLAH"] },
      { id: 'yn-12', lines: ["ANTA MISBAAHU SUDUURI", "LABAYKA YAA RASUULA LLAH"] },
      { id: 'yn-13', lines: ["YA HABEEBII YAA MUHAMMAD", "LABAYKA YAA RASUULA LLAH"] },
      { id: 'yn-14', lines: ["YA 'ARUUSAL KHAAFIQAYNI", "LABAYKA YAA RASUULA LLAH"] },
      { id: 'yn-15', lines: ["YA MU'AYYAD YA MUMAJJAD", "LABAYKA YAA RASUULA LLAH"] },
      { id: 'yn-16', lines: ["YA IMAAMAL QIBLATAYNI", "LABAYKA YAA RASUULA LLAH"] },
    ]
  },
  {
    id: 'qaseedatun-mad-hiyatun',
    title: 'QASEEDATUN-MAD-HIYATUN',
    verses: [
      { id: 'qm-1', lines: ["Fa Muhammadu Naa Huwa Seyyidunaa", "Fal-'izzu Lanaa Li Ijaabati-hi"] },
      { id: 'qm-2', lines: ["Asubhu Badaa Min Tol-hatihi", "Wa Laylu Dajaa Min Wafratihi"] },
      { id: 'qm-3', lines: ["Faaqo Rusula Fodlan Wa Ulan", "Ah-daa Subula Li Dalaa-latihi"] },
      { id: 'qm-4', lines: ["Kanzul Karami Maolaa Ni-hami", "Haadil Umami Li Shareehatihi"] },
      { id: 'qm-5', lines: ["Azkaa Nasabi 'ahlaali Asabi", "Kulluli Arabi Fii Khidmati-hi"] },
      { id: 'qm-6', lines: ["Naala Sharafa Wallahu 'afaa", "'am-maa Salafa Min Ummati-hi"] },
      { id: 'qm-7', lines: ["Sa-hati Shajaru Notoqol Ajaru", "Shugol Qomoru Bi-ishaaratihi"] },
      { id: 'qm-8', lines: ["Jibreelu Ataa Laylatal Asraa", "Farobbu Da-'aa Li Hadrati-hi"] },
    ]
  },
  {
    id: 'solli-yaa-waa',
    title: 'SALLI YAH WAA',
    verses: [
      { id: 'syw-1', lines: ["Solli Yaa waa-iba sofaa Maa mahaa Laahu Ao afaa", "Linnabi ma'adinil wafaa Zamba man kaana Asraafa"] },
      { id: 'syw-2', lines: ["Yaa nabiyyaa mukammalaa Haawiyal fadlin wal ulaa", "Yaa rasuula mujallalan Wal moqomal Musharrafaa"] },
      { id: 'syw-3', lines: ["Yaa habeeban muqorrabaa Yaa najiyyaa muhazzabaa", "Yaa sofiyyaa muhabbabaa Aaza majdan mutahafaa"] },
      { id: 'syw-4', lines: ["Yaa jemeelan mukarramaa Yaa Azeeman mufakhamaa", "Yaa jeleelan muhazzomaa Jaaza Hujban warof-rofa"] },
      { id: 'syw-5', lines: ["Saamiyal Qodri waz Zuraa Khayra maa-shin alaa tharaa", "Ashrafa N-naasi wal waraa Akrama Rusli laa khafaa"] },
      { id: 'syw-6', lines: ["Anta durrun wa-jaoharu Anta A'ala wa Akbaru", "Anta Aglaa wa af-kharu Anta lillahi Mustaafa"] },
      { id: 'syw-7', lines: ["Anta Sultaanu Ruslihi Anta Meesaanu adlihi", "Anta Meesabu fadlihi Anta Asnaa Wa ashrofaa"] },
      { id: 'syw-8', lines: ["Anta Nnurun Muto-haru Anta fii rusli Ash'aru", "Anta fil kaoni Mazharu Anta Asmaa wa altofaa"] },
      { id: 'syw-9', lines: ["Yaa shefihal Khalahiqi Ya kitaabal haqohiqi", "Fii jemeehi Daqoohiqi Kun minal hajzi mus-hifaa"] },
      { id: 'syw-10', lines: ["Soodiqol qaoli wal fihaal Abdilil qotha Bil wisoli", "Baa-iyal qoddi wal jamaal Azhibi Sodda wal jafaa"] },
      { id: 'syw-11', lines: ["Wadnu Yaa faa'iqo Zzibaa Wa ilaa Nnuuri qorribaa", "Wak-shifil hujba wal khibaa Tamimil qosda bil wafaa"] },
      { id: 'syw-12', lines: ["Khaadimu minka yar'tajii Faf'tehil Baaba yuulaju", "Wa ilaal hujbi yal-tajii Bin-Nabiyyii wa Mustafaa"] },
      { id: 'syw-13', lines: ["Wag-firi Zamba war'ami Bi-rasuulin Mu'azomi", "Wasturil Ayba wak-rimi Kullama zalla Ao Hafaa"] },
      { id: 'syw-14', lines: ["Wa Solaatul Ilaahi maa Tag'sha badran Muta'mamaa", "Saja'a Tayru fil himaa Faaqo Nuuhan wa Yusuufaa"] },
      { id: 'syw-15', lines: ["Wa Kazaal Aali Kullamaa Ao muheebu tara'namaa", "Sakabal qotru ao amaa Solli yaa waa'hiba Ssofaa"] },
    ]
  },
  {
    id: 'jawaa-iruna',
    title: 'JAWAA-IRUNAH',
    verses: [
      { id: 'ji-1', lines: ["Qosodtu Wa-alaamu-l-Guyuubi Bimursodi", "Jawaarihuna Tumha Bijaahi Muhammadi"] },
      { id: 'ji-2', lines: ["Lin-nafsii Wal-Ikhwaani Ashrofa Moqsodi", "Jawaarihuna Tumha Bijaahi Muhammadi"] },
      { id: 'ji-3', lines: ["Bimadhi-n-Nabiyyil Aashimiyyi Muhayyadi", "Jawaarihuna Tumha Bijaahi Muhammadi"] },
      { id: 'ji-4', lines: ["Ziquu Bimunaakum Inna Zikra Muhammadi", "Jawaarihuna Tumha Bijaahi Muhammadi"] },
      { id: 'ji-5', lines: ["Yafuusu Bihil Musgii Lahu Wal-Muhadizu", "Jawaarihuna Tumha Bijaahi Muhammadi"] },
      { id: 'ji-6', lines: ["Laqod Baharo-l-Aniwaaro Nuuru Shuhaa-hihi", "Jawaarihuna Tumha Bijaahi Muhammadi"] },
      { id: 'ji-7', lines: ["Waqo-oma Bihamri Llahi Ja'da Ditilaahihi", "Jawaarihuna Tumha Bijaahi Muhammadi"] },
      { id: 'ji-8', lines: ["Falaa Khayra Illaa Fil Maseeri Tibaahihi", "Jawaarihuna Tumha Bijaahi Muhammadi"] },
      { id: 'ji-9', lines: ["Sahaa-datunaa Mash-rutotun Bi-tibaahihi", "Jawaarihuna Tumha Bijaahi Muhammadi"] },
      { id: 'ji-10', lines: ["Wahal Yanbuzu-l-Bunyaanu illaa alaal Hunsi", "Jawaarihuna Tumha Bijaahi Muhammadi"] },
      { id: 'ji-11', lines: ["Ahid Zikro Khayril Khalqi Fal-uudu Ahmada", "Jawaarihuna Tumha Bijaahi Muhammadi"] },
      { id: 'ji-12', lines: ["Walil-qolbi Fee Tazkaari Waslun Mujaddadu", "Jawaarihuna Tumha Bijaahi Muhammadi"] },
      { id: 'ji-13', lines: ["Wa aqsim alaa Haqqi Walasta Tufan-nadu", "Jawaarihuna Tumha Bijaahi Muhammadi"] },
      { id: 'ji-14', lines: ["Yameenan Laqod Jalla-n-Nabiyyu Muhammadu", "Jawaarihuna Tumha Bijaahi Muhammadi"] },
      { id: 'ji-15', lines: ["Minal Hubbi Wa-tashreefi Fi Rutbatil Hulyaa", "Jawaarihuna Tumha Bijaahi Muhammadi"] },
    ]
  },
  {
    id: 'allahuma-yaa-robbi',
    title: 'ALLAHUMO YAH ROBBI',
    verses: [
      { id: 'ayr-1', lines: ["Allahuma Yaa Roobbi sollia ala Muhammadiin", "Waseyyidi Saa-daati Nabiyyi Muhammadin"] },
      { id: 'ayr-2', lines: ["Allahuma Solli Kulla Yaomi Wa-laylati", "Wa-baarik Wasellim lil-habeebi Muhammadin"] },
      { id: 'ayr-3', lines: ["Allahuma solli in the Morning wa in the Night", "Upon You my Sweet Heart Haamidin Wa Muhammadin"] },
      { id: 'ayr-4', lines: ["The Dust of your Sandal my Beloved wa my Darling", "On top of my Forehead more than Silver wa Diamond"] },
      { id: 'ayr-5', lines: ["I Envy Baa-bakar and Umara Because of You", "I Envy Usmana and Aliyya Li-ahmadi"] },
      { id: 'ayr-6', lines: ["Agisnii Agisnii Yaa Muroodi wa Musnadi", "Li Annaka Baabun Lil-ilaahi wa Maajidi"] },
      { id: 'ayr-7', lines: ["The Generalissimo of Nabiyyina all of them", "My Master my Lover Ya Abeebi Muhammadi"] },
      { id: 'ayr-8', lines: ["I Love You Muhammad more than Nafsii wa Property", "The Light of the Universe your Excellency Seyyidi"] },
      { id: 'ayr-9', lines: ["Wa Haza Khadimu Jaa Ilaykum Tawadduhan", "Agisnii Qobilnii Zal-ayaadi Mumajjadi"] },
      { id: 'ayr-10', lines: ["Eba yin Muhammad ee-ni tin fe Muhammadan", "Kinu Ololufe dun Ahmadi wa Muhammadii"] },
      { id: 'ayr-11', lines: ["Beru Ban Saa Aare Fal-yusolli Li'ahamadi", "Oba alala fiiya yio wo e san Bi'ahmadi"] },
      { id: 'ayr-12', lines: ["Bosi ba po pupo Fal-tusolli Li'ahmadi", "Wallahi Tallahi oo Doloowo in Manifold"] },
      { id: 'ayr-13', lines: ["Bo ban Fali-janna Fal-tusolli Li'ahmadi", "Fa A'lan Wa Sa'lan lao Woleola bi Seyyidi"] },
      { id: 'ayr-14', lines: ["Bota baa po Pupo Fal'tusolli Li'ahmadi", "The Soldier of Allah won gbe en-jah Bi'ahmadi"] },
      { id: 'ayr-15', lines: ["Wa Solli Alayhi yaa Ilaahi wa Khaliqi", "Wa aali wa Sahabi bal wa Ummati Ahamadi"] },
    ]
  },
  {
    id: 'ike-oluwa-ati-ola',
    title: 'IKE OLUWA ATI OLA',
    verses: [
      { id: 'ioa-1', lines: ["FAHULUN FAHULUN FAHULUN FAHAL", "FAHULUN FAHULUN FAHULUN FAHAL"] },
      { id: 'ioa-2', lines: ["IKE OLUWA ATI OLA K'O BA ANNABI MI 2x", "ATI AWON OBINRIN RE IYA MUMINI"] },
      { id: 'ioa-3', lines: ["IYONU OLUWA K'O BA KASIMI 2x", "AKOBI MUHAMMAD T'O JE DAUDU FUN"] },
      { id: 'ioa-4', lines: ["K'O TUN BA ABDULLAHI OL'ORUKO BABA 2x", "BABA T'O BI MUHAMMAD ASAJU EDA"] },
      { id: 'ioa-5', lines: ["JARE OLUWA DAKUN SE'KE SE'GE RE 2x", "FUN OMO MARIYATA IBRAHIMUN"] },
      { id: 'ioa-6', lines: ["ANU OLUWA K'O BA FATIMAH 2x", "ATI UMMU KULTHUM ATI ZAINABU"] },
      { id: 'ioa-7', lines: ["RUKAYYATU DAKUN JARE OLUWA MI 2x", "PAKO 'KE FI WON BO AWON MEJEJE"] },
      { id: 'ioa-8', lines: ["EJE AGBA MUHAMMAD DAGBO KA TELE 2x", "ENI TO WAHALA LORI AWA EDA"] },
      { id: 'ioa-9', lines: ["KA ROJU KA MURA AWA MUMINI 2x", "AWA L'A O MA LEKE AWON KAFIRI"] },
    ]
  },
  {
    id: 'solluu-alayhi',
    title: 'SALLU ALAYHI',
    verses: [
      { id: 'sa-1', lines: ["SOLLUU ALAYHI WASELIMUU TESLEEMA", "SOLLUU ALAYHI WASELIMUU TESLEEMA"] },
      { id: 'sa-2', lines: ["YAA RABBANAA BIMUHAMADIN BIMUHAMADIN", "ANSIL ALAYNAA RAHMATAN WA SALAAMAA"] },
      { id: 'sa-3', lines: ["WABI'AALIHI WABISA'BIHI WAL UMMATI", "ANSIL ALAYNAA RAHMATAN WA SALAAMAA"] },
      { id: 'sa-4', lines: ["WABI SHAYKHINAA BARHAMA THUMMA AHMADA", "ANSIL ALAYNAA RAHMATAN WA SALAAMAA"] },
      { id: 'sa-5', lines: ["WABITAAJINAA WAKAMAALINA WABIJAAMIHI", "ANSIL ALAYNAA RAHMATAN WA SALAAMAA"] },
      { id: 'sa-6', lines: ["BIMUBASHIRIN WASA'DINAA WA OLOHUNGBEBE", "ANSIL ALAYNAA RAHMATAN WA SALAAMAA"] },
      { id: 'sa-7', lines: ["WAL ASFIYAA'I KIBAARIHIM WA SIGAARIHIM", "ANSIL ALAYNAA RAHMATAN WA SALAAMAA"] },
      { id: 'sa-8', lines: ["WAL AOLIYAA'I RIJAALIHIM WA NISAA'IHIM", "ANSIL ALAYNAA RAHMATAN WA SALAAMAA"] },
      { id: 'sa-9', lines: ["WAL ATQIYAA'I BAYAADIHIM WASAWAADIHIM", "ANSIL ALAYNAA RAHMATAN WA SALAAMAA"] },
    ]
  },
  {
    id: 'come-for-me',
    title: 'COME FOR ME',
    verses: [
      { id: 'cfm-1', lines: ["YA MUHAMMADU COME FOR ME (2CE)", "YA RASUULULLAH LIFT ME UP FROM THE DARKNESS OF SINFUL WORLD"] },
      { id: 'cfm-2', lines: ["YA MUHAMMADU COME FOR ME (2CE)", "YA MUHAMMADU BE FOR ME SHOW ME GUIDANCE AND SHOW ME LOVE"] },
      { id: 'cfm-3', lines: ["MY BELOVED MY NUMBER ONE (2CE)", "NUMERO UNO MY MUSTAFA YOU'RE MY DARLING YA MURTADA"] },
      { id: 'cfm-4', lines: ["YOUR SIGNATURE INSIDE MY HEART (2CE)", "AND YOUR SANDALS UPON MY HEAD THAT'S MY GLORY AND THIS MY CROWN"] },
      { id: 'cfm-5', lines: ["YA MUHAMMADU BE MY FRIEND (2CE)", "YA MUHAMMADU YOU'RE MY LOVE YOU'RE MY SWEETHEART, YOU'RE MY DARLING"] },
      { id: 'cfm-6', lines: ["I'M NOT HOPELESS I HOPE IN YOU (2CE)", "I AM A WEAKLING BUT STRONG WITH YOU HASBIYYALLAAHU WANABBI"] },
      { id: 'cfm-7', lines: ["YA RASUULULLAH I AM HERE (2CE)", "YA RASUULULLAH SAVE MY SOUL FROM ALL TRIALS AND TRIBULATIONS"] },
      { id: 'cfm-8', lines: ["YA RASUULULLAH VIE FOR ME (2CE)", "YA MUHAMMADU VOUCH FOR ME YA MUHAMMADU INTERCEDE"] },
      { id: 'cfm-9', lines: ["YA MUHAMMADU INTERCEDE (2CE)", "ON BEHALF OF ALL ALMUBINS BIHAQI NUURIL MUTALSAMI"] },
      { id: 'cfm-10', lines: ["AT YOUR DOORSTEP WE ALL HAVE COME (2CE)", "YOUR COMMUNITY ARE SUFFERING YA MUHAMMADU INTERCEDE"] },
      { id: 'cfm-11', lines: ["YOUR COMMUNITY ARE BEEN TORTURED (2CE)", "YOUR COMMUNITY ARE DOWNTRODDEN YA MUHAMMADU INTERCEDE OUR ENEMIES ARE KILLING US (2CE) KILLING OUR CHILDREN AND BOMBING US YA MUHAMMADU STAND FOR US"] },
      { id: 'cfm-12', lines: ["YA MUHAMMADU INTERCEDE (2CE)", "YA RASUULULLAHI STAND FOR US YOU ARE THE LIGHT OF MUTALSAMI"] },
      { id: 'cfm-13', lines: ["BILLIONS SALAATILI FAATIHІ (2CE)", "UPON MUHAMMMADI EVERYDAY ANTA NUURUL MUTALSAMI"] },
    ]
  },
  {
    id: 'eyonbo-annabi',
    title: 'EYONBO ANABI',
    verses: [
      { id: 'ea-1', lines: ["OSU BIBI ANABI NA LAWAA FUN", "OSU BIBI ANABI NA LAWAA FUN KA PE JO KAJOKO TORI MUHAMMAD OSU BIBI ANABI LAWA FUN"] },
      { id: 'ea-2', lines: ["OSE BIBI ANABI NA LAWA FUN", "OSE BIBI ANABI NA LAWA FUN KANA WO KA NARA TORI MUHAMMAD OSE BIBI ANABI LAWA FUN"] },
      { id: 'ea-3', lines: ["OJO IBI ANABI NA LAWA FUN", "OJO BIBI ANABI LAWA BI FUN KA SASALATU FUN KA SE QOSIDA OJO IBI ANABI LAWA FUN"] },
      { id: 'ea-4', lines: ["IYA TOBI MUHAMMA LABA DUPE", "BABA TO BI MUHAMMA LABA DUPE BIMO ΒΙΜΟ Ο ΒΕΝΙ ΚΑΝ TOTO MUHAMMA IYA TOBI MUHAMMA LABA DUPE"] },
      { id: 'ea-5', lines: ["OMO AAMINATU LABA DUPE", "OMO ABDULLAHI LOLOLA FE OLOLA O DE NI KAN TOTO MUHAMMA OMO AAMINATU LAGBADE FUN"] },
      { id: 'ea-6', lines: ["OKO KHADIJATU NA LASIWAJU", "OKO AISHATU NA LASAAJU OBINRIN OFE NIKAN TOTO MUHAMMA OKO HAAFUSATU LASAAJU"] },
      { id: 'ea-7', lines: ["BABA FATIMATU NA LA GBOLAFUN", "BABA BUREEMO NA LOGAAWA ΟΜΟ ΚΑΝ ONI BABA TOTO MUHAMMA BABA QOOSIMU NA LOLORI"] },
      { id: 'ea-8', lines: ["ORE ABU BAKARE NA LORE WA", "ORE UMARU NAA LORE WA ΕΝΙΚΑΝ Ο NI ORE BI TI MUHAMΜΜΑ ORE JIBRAHILU NA LORE WA"] },
      { id: 'ea-9', lines: ["ADEKILEKUN NA LARAN SAYE", "ELEYINJU ANU LARAN SAYE AL MUSITAFAA LARIN EDA E MOSHOBALAAJE NA LAGBADE FUN"] },
      { id: 'ea-10', lines: ["ADUN BARIN NA LOGAAWA O", "ALAPERIRE NA LOGAAWA OLOLA O DE NI KAN TOTO MUHAMMA ISELERUU ANU LOGAAWA"] },
      { id: 'ea-11', lines: ["ASIWAAJU EDA LOLA DA PE", "ASIWAAJU EDA LOLA DA PE ODA MUSA - KOTO MUHAMMA ODA ISA - KOTO MUHAMMA ODA LI ARASHI KOTO MUHAMΜΑ ASIWAAJU EDA LOLA DA PE"] },
      { id: 'ea-12', lines: ["TORI MAOLUDI NA LABADEBI", "TORI MADIU NA LASEN WA ORO OFIN KO LEYI O IFE MA LO KAN TORI MAOLUDI NA LABADEBI"] },
      { id: 'ea-13', lines: ["TORI MAOLUDI NA LABADEBI", "TORI MADIU NA LASEN WA WARA FAH NAA LAKA KA ZIKIRAKA TORI MAOLUDI NA LABADEBI"] },
      { id: 'ea-14', lines: ["EJE AYON BO ANABI OMO NLA", "EJE AYON BO ANABI OMO NLA BOWO LOFEENI YONBO MUHAMΜΑ EJE AYONBO ANABI OMO NLA BOMO LOFEEBI YONBO ANABI EJE AYONBO ANABI OMO NLA BO LA LOBAN FE YONBO MUHAMMA EJE AYON BO ANABI OMO NLA"] },
      { id: 'ea-15', lines: ["EMI O YONBO ANABI KOLA O DE", "EJE AYON BO ANABI OMO NLA EJE AYON BO ANABI OMO NLA EJE AYON BO ANABI OMO NLA KAYE WA ORORUN KORUN SI TUN DUN EJE AYONBO ANABI OMO NLA"] },
      { id: 'ea-16', lines: ["ΙΝΑΑ ΑΤΑΥΝΑΑΚΑ AL KAOSARA", "EJE AYON BO ANABI OMO NLA MUHAMMADAAHU OLOPO EWA EJE AYON BO ANABI OMO NLA YA ROBI SOLI ALA MUHAMMA EJE AYON BO ANABI OMO NLA WA ALAA AALI PELU SAHABI EJE AYON BO ANABI OMO NLA"] },
    ]
  },
  {
    id: 'yaa-robbi',
    title: 'YAA ROBBI',
    verses: [
      { id: 'yr-1', lines: ["YAA ROBBI AYYI'I LANAA MIN AMRINAA RASHADAN", "WA'AJLI MA'UNATAKAL UZMAA LANA MADADAN"] },
      { id: 'yr-2', lines: ["WALA TAKILNA ILAA TAD-BEERI ANFUSINAA", "FAN-NAFSU TA'JUSU AN ISLAAHI MAA FASADA"] },
      { id: 'yr-3', lines: ["ANTAL ALEEMU WA QOD WAJA'ATU YAA AMALII", "ILA RAJAA-IKA QOLBAN SAA-ILAN WAYADAA"] },
      { id: 'yr-4', lines: ["FALA TARUDANNAHA YAA ROBBI KHAAIBATAN", "FABA'RU JUUDIKA YURWI KULLA MAA WARADA"] },
    ]
  },
];

export const TEXT_SIZE_CLASSES: Record<TextSize, { base: string; leading: string }> = {
  [TextSize.Small]: { base: 'text-sm', leading: 'leading-6' },
  [TextSize.Medium]: { base: 'text-base', leading: 'leading-7' },
  [TextSize.Large]: { base: 'text-lg', leading: 'leading-8' },
};